### ISSUE TITLE
Spin up a self-hosted analytics tool

### ISSUE THREAD

**Issue by ole-nov** [mento-protocol/mento-web#32]
**Description**

Set up a self-hosted instance of Plausible analytics for mento.org.

**Acceptance criteria**

- [ ] We have VM running in Google Cloud
- [ ] The VM should locally run all other components required (like database, cache, etc) in Docker
- [ ] The VM should run Plausible in Docker
- [ ] We have setup a mento.org subdomain for analytics pointing to the VM's external IP

**Comment by bayological** [comment]
@bowd I have no access to our GCP org, so can't move forward with this. Please give me access when you can.

**Comment by bayological** [comment]
I'm dropping this because I can't move forward. A new VM(vm-plausible-02) has been created and has the plausible container running. However, I cannot reach it from the internet; I've also checked firewall rules, and all are allowed on port 80. The docs mention setting the baseUrl to the domain we want to monitor, I can't do this either as I cannot get access to manage DNS settings on the domain mento.org. Maybe we can ask cLabs IT for assistance unless someone else wants to pick this up. @bowd @nvtaveras @ole-nov
